name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, xml, ctype, json
          coverage: xdebug
          tools: composer:v2

      - name: Cache & Install Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-version }}-composer-
      - run: composer install --prefer-dist --no-progress --no-interaction


  tests:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.4']
    steps:
      - name: Run Codeception tests
        run: vendor/bin/codecept run --coverage-xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./tests/_output/coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}

  code-quality:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Check code style (PHP-CS-Fixer)
        run: composer cs:check

  rector:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run Rector (dry-run)
        run: composer rector:check
